2019-12-17 18:31:22,009-ERROR-my_log.py-python11-日志信息:请求报错了：HTTPConnectionPool(host='119.23.241.154', port=8080): Max retries exceeded with url: /futureloan/mvc/api/member/login?mobilephone=15096099000&pwd=123456 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020FC7409518>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
